plugins {
    id 'java'
}

group = 'com.gamer0kayf1n3'
version = '1.0.0'

repositories {
  maven {
    name = 'papermc'
    url = 'https://repo.papermc.io/repository/maven-public/'
  }
}

dependencies {
  compileOnly 'com.velocitypowered:velocity-api:3.5.0-SNAPSHOT'
  annotationProcessor 'com.velocitypowered:velocity-api:3.5.0-SNAPSHOT'
}